version: "3.8"

services:
  netcdf-base:
    build:
      context: .
      args:
        BASE_IMAGE: "${BASE_IMAGE}"
        CURL_VERSION: "${CURL_VERSION}"
        DAP_VERSION: "${DAP_VERSION}"
        GDAL_VERSION: "${GDAL_VERSION}"
        HDF5_VERSION: "${HDF5_VERSION}"
        NETCDF_VERSION: "${NETCDF_VERSION}"
        NCO_VERSION: "${NCO_VERSION}"
        PROJ_VERSION: "${PROJ_VERSION}"
    command: "'tail -f /dev/null'"
    entrypoint: ["/bin/bash", "-c"]
    image: "onaci/ereefs-netcdf-base:dev"

