#!/bin/bash

# Allow our docker build to add Open Containers-style labels
# See: https://github.com/opencontainers/image-spec/blob/main/annotations.md

BUILD_TIMESTAMP="$(date --rfc-3339=seconds)"
SAFE_TIMESTAMP="$(echo $BUILD_TIMESTAMP | sed 's/ /T/g' | sed 's/:/-/g' | sed 's/\+.*//')"
SOURCE_URL="$(git remote get-url origin || true)"
VERSION_TAG="${SOURCE_BRANCH}_v${SAFE_TIMESTAMP}-${SOURCE_COMMIT}"

# Identify our BASE_IMAGE argument
BASE_IMAGE="debian:12-slim"
DOCKER_TAG="${DOCKER_TAG:-}"
if [[ -n "${DOCKER_TAG}" ]] && [[ "${DOCKER_TAG}" != "latest" ]]; then
    # Prepend the non-default docker tag to the versioned docker tag
    VERSION_TAG="${DOCKER_TAG}_${VERSION_TAG}"

    # Derive the BASE_IMAGE from the DOCKER_TAG
    if [[ $DOCKER_TAG =~ ^r-base- ]]; then
        BASE_IMAGE=$(echo "${DOCKER_TAG}" | sed 's/^r-base-/r-base:/')
    else
        BASE_IMAGE=$(echo "${DOCKER_TAG}" | sed 's/\-/:/1')
    fi
fi

# Build our customised docker image
docker build --pull \
    --build-arg "BASE_IMAGE=${BASE_IMAGE}" \
    --label "org.opencontainers.image.authors=${BUILD_AUTHORS:-CSIRO eReefs Team}" \
    --label "org.opencontainers.image.branch=${SOURCE_BRANCH}" \
    --label "org.opencontainers.image.buildhost=${DOCKER_REPO}" \
    --label "org.opencontainers.image.created=${BUILD_TIMESTAMP}" \
    --label "org.opencontainers.image.licenses=BSD-3-Clause" \
    --label "org.opencontainers.image.revision=${SOURCE_COMMIT}" \
    --label "org.opencontainers.image.source=${SOURCE_URL}" \
    --label "org.opencontainers.image.title=${DOCKER_REPO:-ereefs/netcdf-base}" \
    --label "org.opencontainers.image.url=https://github.com/eReefs/netcdf-base" \
    --label "org.opencontainers.image.vendor=CSIRO" \
    --label "org.opencontainers.image.version=${VERSION_TAG}" \
    -f ${DOCKERFILE_PATH} \
    -t ${IMAGE_NAME} \
    .
